/*
 * generated by Xtext 2.12.0
 */
package org.xtext.demo.validation

import com.google.inject.Inject
import org.eclipse.xtext.validation.Check
import org.xtext.demo.interpreter.Calculator
import org.xtext.demo.fsh.Div
import static org.xtext.demo.fsh.FshPackage.Literals.*

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class FshValidator extends AbstractFshValidator {
	
	@Inject Calculator calculator

	@Check
	def checkDivByZero(Div div) {
		val bigDecimal = calculator.evaluate(div.right)
		if (bigDecimal.doubleValue() == 0.0) 
			error("Division by zero detected.", DIV__RIGHT)
	}
	
}
