/*
 * generated by Xtext 2.12.0
 */
package org.xtext.demo


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class FshStandaloneSetup extends FshStandaloneSetupGenerated {

	def static void doSetup() {
		new FshStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
