/*
 * generated by Xtext 2.12.0
 */
package org.xtext.demo.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.demo.FshRuntimeModule
import org.xtext.demo.FshStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class FshIdeSetup extends FshStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new FshRuntimeModule, new FshIdeModule))
	}
	
}
